# -*- coding: utf-8 -*-
"""Modern_Implementation_ Grover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vCjgCyuTp-muUTPLsr6NuYnLt0DgCVJD
"""

!pip install qiskit qiskit-aer numpy matplotlib

from qiskit_aer import Aer

from qiskit.visualization import plot_histogram

# Create the clasical grayscale image
import numpy as np
image=np.array([[0,100],[200,255]])
print("Input image:")
print(image)

from qiskit import QuantumCircuit, transpile

#Allocate 8 intensity qubits and 2 position qubits
#q0-q7 Intensity
#q8: X coordinate
#q9 : Y coordinate

qc= QuantumCircuit(10,10) # Total 10 qubits and 10 classical registers

# Create equal superposition of four positions
qc.h([8,9])

from qiskit import QuantumCircuit

image = [
    [0, 100],
    [200, 255]
]

encoding = QuantumCircuit(10)

# Position superposition
encoding.h([8, 9])

# Encode each pixel
for y in range(2):
    for x in range(2):
        binary = format(image[y][x], "08b")

        # Convert the selected position to controls |11>
        if y == 0:
            encoding.x(9)
        if x == 0:
            encoding.x(8)

        # Write the intensity bits
        for bit_index, bit in enumerate(binary):
            if bit == "1":
                target = 7 - bit_index
                encoding.mcx([9, 8], target)

        # Restore position
        if x == 0:
            encoding.x(8)
        if y == 0:
            encoding.x(9)

print("MCX count:", encoding.count_ops().get("mcx", 0))
print("Circuit operations:", encoding.count_ops())

from qiskit import transpile
from qiskit_aer import Aer
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt

# Make a copy so the original encoding circuit stays unmeasured
measured = encoding.copy()
measured.measure_all()

simulator = Aer.get_backend("qasm_simulator")
compiled = transpile(measured, simulator)

result = simulator.run(
    compiled,
    shots=8192
).result()

counts = result.get_counts()

print("NEQR measurement counts:")
print(counts)

plot_histogram(counts)
plt.show()

import matplotlib.pyplot as plt

# We set the figure size directly inside Qiskit's plot_histogram to improve visual resolution
fig = plot_histogram(counts, figsize=(10, 5),title="Equal superposition of the four pixel pairs")
display(fig)

from qiskit.quantum_info import Statevector

state = Statevector.from_instruction(encoding)

print("Number of amplitudes:", len(state.data))
print("Non-zero amplitudes:", sum(abs(a) > 1e-10 for a in state.data))

import numpy as np

for index, amplitude in enumerate(state.data):
    if abs(amplitude) > 1e-10:
        bitstring = format(index, "010b")
        probability = abs(amplitude) ** 2

        print(
            f"State: |{bitstring}> | "
            f"Amplitude: {amplitude} | "
            f"Probability: {probability:.2f}"
        )

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector

oracle = QuantumCircuit(2)

# Map target |00> to |11>
oracle.x(0)
oracle.x(1)

# Phase flip on |11>
oracle.cz(0, 1)

# Restore the original basis labels
oracle.x(0)
oracle.x(1)

print(oracle.draw(output="text"))

print(oracle.draw(output="text"))
print(oracle.count_ops())

from qiskit.quantum_info import Statevector

initial_state = Statevector.from_label("++")
final_state = initial_state.evolve(oracle)

print("Initial state:")
print(initial_state)

print("\nFinal state:")
print(final_state)

from qiskit import QuantumCircuit

def diffuser():
    qc = QuantumCircuit(2)

    qc.h([0, 1])
    qc.x([0, 1])

    # Phase-flip |11>
    qc.cz(0, 1)

    qc.x([0, 1])
    qc.h([0, 1])

    return qc

diff = diffuser()
print(diff.draw(output="text"))

from qiskit.quantum_info import Statevector

initial_state = Statevector.from_label("++")
after_oracle = initial_state.evolve(oracle)
after_diffuser = after_oracle.evolve(diff)

print("After oracle:")
print(after_oracle.data)

print("\nAfter diffuser:")
print(after_diffuser.data)

from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer

# Prepare the initial equal superposition
qc = QuantumCircuit(2, 2)
qc.h([0, 1])

# Apply oracle and diffuser
qc.compose(oracle, inplace=True)
qc.compose(diff, inplace=True)

# Measure both qubits
qc.measure([0, 1], [0, 1])

simulator = Aer.get_backend("qasm_simulator")
compiled = transpile(qc, simulator)
result = simulator.run(compiled, shots=1024).result()

print(result.get_counts())
print(qc.draw(output="text"))